name: FastApi Deploy to AWS EC2 via CodeDeploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if FastAPI is installed
        run: |
          python -c "import fastapi" || (echo 'FastAPI is not installed' && exit 1)

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Authenticate AWS CLI
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Package application
        run: aws deploy push --application-name ${{ vars.APPLICATION_NAME }} --s3-location s3://${{ vars.S3_BUCKET }}/${{ vars.ARTIFACTS_PATH }} --ignore-hidden-files

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ vars.APPLICATION_NAME }} \
            --deployment-group-name dev \
            --s3-location bucket=${{ vars.S3_BUCKET }},key=${{ vars.ARTIFACTS_PATH }},bundleType=zip \
            --region ${{ secrets.AWS_DEFAULT_REGION }}
